'use strict';
const $ = id => document.getElementById(id);
const state = {groups:[], decisions:{}, visible:[], key:null, occurrence:0, token:'', output:'', zoom:100};
function toast(message, error=false){const el=$('toast');el.textContent=message;el.className='toast visible'+(error?' error':'');setTimeout(()=>{el.className='toast'},4500)}
async function post(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Normalize-Review-Token':state.token},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||response.statusText);return result}
function decision(key){return state.decisions[key]?.decision || 'pending'}
function filteredGroups(){let groups=state.groups.filter(g=>{
  const status=decision(g.key), statusFilter=$('statusFilter').value, repairs=$('repairFilter').value, evidence=$('evidenceFilter').value;
  if(statusFilter!=='all'&&status!==statusFilter)return false;
  if(repairs==='any'&&!g.repair_count)return false;
  if(repairs==='all-proposed'&&g.repair_count!==g.count)return false;
  if(repairs==='all-verified'&&g.verified_repair_count!==g.count)return false;
  if(repairs==='mixed'&&!(g.repair_count>0&&g.repair_count<g.count))return false;
  if(repairs==='none'&&g.repair_count!==0)return false;
  if(evidence==='suggested'&&!g.suggested_count)return false;
  if(evidence==='eligible'&&(!g.eligible_count||g.already_known))return false;
  return g.word.toLocaleLowerCase().includes($('search').value.trim().toLocaleLowerCase())
});
  const sort=$('sort').value;
  groups.sort((a,b)=>sort==='alphabetical'?a.word.localeCompare(b.word):sort==='suggestion'?(b.suggested_count-a.suggested_count||b.count-a.count||a.word.localeCompare(b.word)):(b.count-a.count||b.suggested_count-a.suggested_count||a.word.localeCompare(b.word)));
  return groups
}
function renderList(){state.visible=filteredGroups();$('listSummary').textContent=`${state.visible.length.toLocaleString()} / ${state.groups.length.toLocaleString()} forms`;const bulkCandidates=bulkEligible(state.visible);$('bulkReject').disabled=!bulkCandidates.length;$('bulkReject').textContent=`Bulk reject ${bulkCandidates.length.toLocaleString()} verified repair-only forms`;const list=$('wordList');list.replaceChildren();for(const g of state.visible){const button=document.createElement('button');button.className='word-item'+(g.key===state.key?' active':'');button.type='button';button.setAttribute('role','option');button.setAttribute('aria-selected',g.key===state.key?'true':'false');const dot=document.createElement('span');dot.className='state-dot '+(decision(g.key)==='pending'?(g.suggested_count?'suggested':'') :decision(g.key));const name=document.createElement('span');name.className='term';name.textContent=g.word;const count=document.createElement('span');count.className='count';count.textContent='×'+g.count;button.append(dot,name,count);if(g.repair_count){const conflict=document.createElement('span');conflict.className='warning-mark';conflict.title=`${g.repair_count} occurrences have proposed repairs`;conflict.textContent='⚠';button.append(conflict)}button.addEventListener('click',()=>selectGroup(g.key));list.append(button)};const vals=Object.values(state.decisions);$('decisionProgress').textContent=vals.length.toLocaleString()+' / '+state.groups.length.toLocaleString();$('acceptProgress').textContent=vals.filter(x=>x.decision==='accepted').length.toLocaleString()}
function bulkEligible(groups){return groups.filter(g=>decision(g.key)==='pending'&&!g.already_known&&g.repair_count===g.count&&g.verified_repair_count===g.count)}
function openBulk(){
  const current=bulkEligible(filteredGroups());
  if(!current.length){toast('No pending, fully verified repair-only words in this filter',true);return}
  state.bulkKeys=current.map(g=>g.key);
  $('bulkCount').textContent=current.length.toLocaleString();
  const skipped=filteredGroups().filter(g=>g.repair_count>0&&!current.includes(g));
  $('bulkExcluded').textContent=skipped.length?`${skipped.length.toLocaleString()} other visible forms are excluded (including mixed evidence or existing decisions). Review those individually.`:'All visible repair-proposal forms meet the bulk safety condition.';
  $('bulkPreview').textContent=current.slice(0,30).map(g=>`${g.word} ×${g.count}`).join(' · ')+(current.length>30?` · … plus ${current.length-30} more`:'');
  $('bulkAcknowledged').checked=false;$('confirmBulk').disabled=true;
  $('bulkDialog').showModal()
}
async function confirmBulk(){
  try{
    const result=await post('/api/bulk-reject',{keys:state.bulkKeys,acknowledged:$('bulkAcknowledged').checked});
    state.decisions=result.decisions;$('bulkDialog').close();renderList();
    if(group())selectGroup(state.key);
    toast(`${result.rejected} lexical forms rejected; occurrence-level repairs unchanged`)
  }catch(err){toast(err.message,true)}
}
function group(){return state.groups.find(x=>x.key===state.key)}
function selectedOccurrence(){const g=group();return g?.occurrences[state.occurrence]}
function changeImage(){const o=selectedOccurrence();if(!o)return;const url='/api/scan?id='+encodeURIComponent(o.id);$('scan').src=url;$('openScan').href=url;$('pageLabel').textContent=o.image;$('selectedPage').textContent='Scan: '+o.page;$('selectedId').textContent=o.id;$('occurrencePosition').textContent=`${state.occurrence+1} of ${group().occurrences.length}`;$('prevOccurrence').disabled=state.occurrence===0;$('nextOccurrence').disabled=state.occurrence>=group().occurrences.length-1;const ctx=$('context');ctx.replaceChildren();ctx.append(document.createTextNode(o.context[0]));const marked=document.createElement('mark');marked.textContent=o.context[1];ctx.append(marked,document.createTextNode(o.context[2]));$('repairInfo').hidden=!o.proposed;$('repairInfo').textContent=o.proposed?`This occurrence has a proposed OCR repair (${o.review_status||'unapproved'}): “${o.word}” → “${o.proposed}”. It cannot serve as the admission evidence.`:'';$('accept').disabled=group().already_known||!o.eligible;$('inspected').checked=false;drawOccurrenceChips()}
function drawOccurrenceChips(){const list=$('occurrenceList');list.replaceChildren();for(const [idx,o] of group().occurrences.entries()){const b=document.createElement('button');b.className='occurrence-chip'+(idx===state.occurrence?' selected':'');b.textContent=o.page.replace(/^.*?_/, 'Page ');if(o.proposed){const s=document.createElement('span');s.className='flag';s.textContent='repair';b.append(s)}else if(o.suggested){const s=document.createElement('span');s.className='flag';s.textContent='suggested';b.append(s)}b.title=o.id;b.addEventListener('click',()=>selectOccurrence(idx));list.append(b)}}
function selectOccurrence(index){if(!group())return;state.occurrence=Math.max(0,Math.min(group().occurrences.length-1,index));changeImage()}
function selectGroup(key){state.key=key;state.occurrence=0;const g=group();if(!g){$('details').hidden=true;$('empty').hidden=false;return}$('details').hidden=false;$('empty').hidden=true;$('word').textContent=g.word;$('meta').textContent=`${g.count} occurrence${g.count===1?'':'s'} · ${g.suggested_count} Codex suggestions · ${g.eligible_count} admission-eligible · ${g.repair_count} repairs proposed`;$('occurTotal').textContent=`${g.occurrences.length} source references`;$('conflictWarning').hidden=!g.repair_count;$('existingWarning').hidden=!g.already_known;const d=state.decisions[g.key];const badge=$('decisionBadge');badge.textContent=d?(d.decision==='accepted'?'Accepted':'Rejected'):'Pending';badge.className='decision-badge '+(d?.decision||'');$('note').value=d?.note||'';$('inspected').checked=false;const supportingIndex=d?.finding_id?g.occurrences.findIndex(x=>x.id===d.finding_id):-1;state.occurrence=supportingIndex>=0?supportingIndex:Math.max(0,g.occurrences.findIndex(x=>x.eligible));$('zoom').value=100;setZoom(100);changeImage();renderList()}
function setZoom(percent){state.zoom=percent;$('scan').style.width=percent+'%'}
async function decide(type){const g=group();if(!g)return;const o=selectedOccurrence();const payload={key:g.key,decision:type,finding_id:type==='accepted'?o.id:null,note:$('note').value,inspected:$('inspected').checked};try{const result=await post('/api/decision',payload);state.decisions=result.decisions;selectGroup(g.key);toast(type==='accepted'?'Accepted word (saved in review progress)':type==='rejected'?'Rejected word (saved in review progress)':'Cleared review decision')}catch(err){toast(err.message,true)}}
function changeBy(delta){if(!state.visible.length)return;let pos=state.visible.findIndex(g=>g.key===state.key);pos=Math.min(state.visible.length-1,Math.max(0,pos+delta));selectGroup(state.visible[pos].key);document.querySelector('.word-item.active')?.scrollIntoView({block:'nearest'})}
async function openExport(){const n=Object.values(state.decisions).filter(x=>x.decision==='accepted').length;$('exportSummary').textContent=`${n} accepted word types will be written to ${state.output}. Existing files will not be overwritten. The shared lexicon is unchanged.`;$('exportDialog').showModal()}
async function exportApproved(){try{const result=await post('/api/export',{});$('exportDialog').close();toast(`Generated ${result.entries} approvals at ${result.path}`)}catch(err){toast(err.message,true)}}
function shortcuts(e){if(document.querySelector('dialog[open]'))return;const tag=document.activeElement?.tagName;if(e.ctrlKey||e.altKey||e.metaKey)return;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT')return;if(e.key==='/'){e.preventDefault();$('search').focus()}else if(e.key==='ArrowDown'){e.preventDefault();changeBy(1)}else if(e.key==='ArrowUp'){e.preventDefault();changeBy(-1)}else if(e.key==='ArrowRight'){e.preventDefault();selectOccurrence(state.occurrence+1)}else if(e.key==='ArrowLeft'){e.preventDefault();selectOccurrence(state.occurrence-1)}else if(e.key.toLowerCase()==='a'){decide('accepted')}else if(e.key.toLowerCase()==='r'){decide('rejected')}else if(e.key.toLowerCase()==='k'){decide('pending')}}
async function init(){try{const response=await fetch('/api/data');if(!response.ok)throw new Error('Could not load review report');const data=await response.json();Object.assign(state,{groups:data.groups,decisions:data.decisions,token:data.token,output:data.output});$('statusFilter').addEventListener('change',renderList);$('repairFilter').addEventListener('change',renderList);$('evidenceFilter').addEventListener('change',renderList);$('sort').addEventListener('change',renderList);$('search').addEventListener('input',renderList);$('prevOccurrence').addEventListener('click',()=>selectOccurrence(state.occurrence-1));$('nextOccurrence').addEventListener('click',()=>selectOccurrence(state.occurrence+1));$('accept').addEventListener('click',()=>decide('accepted'));$('reject').addEventListener('click',()=>decide('rejected'));$('skip').addEventListener('click',()=>decide('pending'));$('zoom').addEventListener('input',()=>setZoom(+$('zoom').value));$('fit').addEventListener('click',()=>{$('zoom').value=100;setZoom(100)});$('bulkReject').addEventListener('click',openBulk);$('cancelBulk').addEventListener('click',()=>$('bulkDialog').close());$('bulkAcknowledged').addEventListener('change',()=>$('confirmBulk').disabled=!$('bulkAcknowledged').checked);$('confirmBulk').addEventListener('click',confirmBulk);$('export').addEventListener('click',openExport);$('cancelExport').addEventListener('click',()=>$('exportDialog').close());$('confirmExport').addEventListener('click',exportApproved);document.addEventListener('keydown',shortcuts);renderList();if(state.groups.length)selectGroup(state.groups[0].key);else{$('empty').textContent='No unknown lexical forms in this reviewed report.'}}catch(err){$('empty').textContent='Could not open reviewer: '+err.message;toast(err.message,true)}}
init();